name: firebase_notes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  provider: ^4.1.3
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.13.7
  uuid: ^2.2.0



  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
